#Configurando as minhas credenciais para o Flask-Mail conectar ao e-mail
mail_server = 'smtp.gmail.com'
mail_port= 587
mail_username = 'your email'
mail_password = 'password generated by gmail using the "App Password" option'